### PR TITLE
The latest version of the project

### PR DESCRIPTION
**Pull request by VurhD-B**
This branch contains the latest code for the demo, with backend and frontend fully integrated and the RestClient file completely updated.

### CODE REVIEW

**Comment by YaBoiLiangZJ** [comment]
looks good to me, test cases are working fine.

**Review by CoolKeed — COMMENTED** [review]
ok looks good to go

**Comment by rmmsia** [comment]
everything seems to work fine, should be ok

**Review by markybaby — COMMENTED** [review]
I see no issues with this for now!

**Comment by Thwompert** [comment]
Yep everything looks good so far

**Pull request merged**
